# .github/workflows/release.yml
name: Release EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r GUI/requirements.txt

      - name: Build executable
        run: |
          cd GUI
          pyinstaller --onefile --windowed winsync.py

      - name: Create ZIP with EXE (for safer download)
        run: |
          7z a winsync-windows.zip GUI/dist/winsync.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: winsync-windows.zip