name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with PyInstaller
        uses: JackMcKew/pyinstaller-action-windows@v1
        with:
          path: ./GUI/winsync.py
