# .github/workflows/build.yml
name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies from GUI/requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r GUI/requirements.txt

      - name: Build executable from GUI/winsync.py
        run: |
          cd GUI
          pyinstaller --onefile --windowed winsync.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: winsync-windows
          path: GUI/dist/